// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package loms

//go:generate minimock -i route256.ozon.ru/project/cart/internal/providers/loms.lomsClient -o loms_client_mock_test.go -n LomsClientMock -p loms

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/cart/internal/models"
)

// LomsClientMock implements lomsClient
type LomsClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateOrder          func(ctx context.Context, userId int64, items []models.CartItem) (i1 int64, err error)
	inspectFuncCreateOrder   func(ctx context.Context, userId int64, items []models.CartItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLomsClientMockCreateOrder

	funcGetNumberOfItemInStocks          func(ctx context.Context, skuId int64) (u1 uint64, err error)
	inspectFuncGetNumberOfItemInStocks   func(ctx context.Context, skuId int64)
	afterGetNumberOfItemInStocksCounter  uint64
	beforeGetNumberOfItemInStocksCounter uint64
	GetNumberOfItemInStocksMock          mLomsClientMockGetNumberOfItemInStocks
}

// NewLomsClientMock returns a mock for lomsClient
func NewLomsClientMock(t minimock.Tester) *LomsClientMock {
	m := &LomsClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLomsClientMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LomsClientMockCreateOrderParams{}

	m.GetNumberOfItemInStocksMock = mLomsClientMockGetNumberOfItemInStocks{mock: m}
	m.GetNumberOfItemInStocksMock.callArgs = []*LomsClientMockGetNumberOfItemInStocksParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsClientMockCreateOrder struct {
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockCreateOrderExpectation
	expectations       []*LomsClientMockCreateOrderExpectation

	callArgs []*LomsClientMockCreateOrderParams
	mutex    sync.RWMutex
}

// LomsClientMockCreateOrderExpectation specifies expectation struct of the lomsClient.CreateOrder
type LomsClientMockCreateOrderExpectation struct {
	mock    *LomsClientMock
	params  *LomsClientMockCreateOrderParams
	results *LomsClientMockCreateOrderResults
	Counter uint64
}

// LomsClientMockCreateOrderParams contains parameters of the lomsClient.CreateOrder
type LomsClientMockCreateOrderParams struct {
	ctx    context.Context
	userId int64
	items  []models.CartItem
}

// LomsClientMockCreateOrderResults contains results of the lomsClient.CreateOrder
type LomsClientMockCreateOrderResults struct {
	i1  int64
	err error
}

// Expect sets up expected params for lomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Expect(ctx context.Context, userId int64, items []models.CartItem) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	mmCreateOrder.defaultExpectation.params = &LomsClientMockCreateOrderParams{ctx, userId, items}
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the lomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Inspect(f func(ctx context.Context, userId int64, items []models.CartItem)) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LomsClientMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by lomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Return(i1 int64, err error) *LomsClientMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LomsClientMockCreateOrderResults{i1, err}
	return mmCreateOrder.mock
}

// Set uses given function f to mock the lomsClient.CreateOrder method
func (mmCreateOrder *mLomsClientMockCreateOrder) Set(f func(ctx context.Context, userId int64, items []models.CartItem) (i1 int64, err error)) *LomsClientMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the lomsClient.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the lomsClient.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	return mmCreateOrder.mock
}

// When sets expectation for the lomsClient.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLomsClientMockCreateOrder) When(ctx context.Context, userId int64, items []models.CartItem) *LomsClientMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	expectation := &LomsClientMockCreateOrderExpectation{
		mock:   mmCreateOrder.mock,
		params: &LomsClientMockCreateOrderParams{ctx, userId, items},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up lomsClient.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LomsClientMockCreateOrderExpectation) Then(i1 int64, err error) *LomsClientMock {
	e.results = &LomsClientMockCreateOrderResults{i1, err}
	return e.mock
}

// CreateOrder implements lomsClient
func (mmCreateOrder *LomsClientMock) CreateOrder(ctx context.Context, userId int64, items []models.CartItem) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, userId, items)
	}

	mm_params := LomsClientMockCreateOrderParams{ctx, userId, items}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, &mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_got := LomsClientMockCreateOrderParams{ctx, userId, items}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LomsClientMock.CreateOrder")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, userId, items)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LomsClientMock.CreateOrder. %v %v %v", ctx, userId, items)
	return
}

// CreateOrderAfterCounter returns a count of finished LomsClientMock.CreateOrder invocations
func (mmCreateOrder *LomsClientMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LomsClientMock.CreateOrder invocations
func (mmCreateOrder *LomsClientMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLomsClientMockCreateOrder) Calls() []*LomsClientMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LomsClientMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockCreateOrderDone() bool {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LomsClientMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LomsClientMock.CreateOrder")
		} else {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder with params: %#v", *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		m.t.Error("Expected call to LomsClientMock.CreateOrder")
	}
}

type mLomsClientMockGetNumberOfItemInStocks struct {
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockGetNumberOfItemInStocksExpectation
	expectations       []*LomsClientMockGetNumberOfItemInStocksExpectation

	callArgs []*LomsClientMockGetNumberOfItemInStocksParams
	mutex    sync.RWMutex
}

// LomsClientMockGetNumberOfItemInStocksExpectation specifies expectation struct of the lomsClient.GetNumberOfItemInStocks
type LomsClientMockGetNumberOfItemInStocksExpectation struct {
	mock    *LomsClientMock
	params  *LomsClientMockGetNumberOfItemInStocksParams
	results *LomsClientMockGetNumberOfItemInStocksResults
	Counter uint64
}

// LomsClientMockGetNumberOfItemInStocksParams contains parameters of the lomsClient.GetNumberOfItemInStocks
type LomsClientMockGetNumberOfItemInStocksParams struct {
	ctx   context.Context
	skuId int64
}

// LomsClientMockGetNumberOfItemInStocksResults contains results of the lomsClient.GetNumberOfItemInStocks
type LomsClientMockGetNumberOfItemInStocksResults struct {
	u1  uint64
	err error
}

// Expect sets up expected params for lomsClient.GetNumberOfItemInStocks
func (mmGetNumberOfItemInStocks *mLomsClientMockGetNumberOfItemInStocks) Expect(ctx context.Context, skuId int64) *mLomsClientMockGetNumberOfItemInStocks {
	if mmGetNumberOfItemInStocks.mock.funcGetNumberOfItemInStocks != nil {
		mmGetNumberOfItemInStocks.mock.t.Fatalf("LomsClientMock.GetNumberOfItemInStocks mock is already set by Set")
	}

	if mmGetNumberOfItemInStocks.defaultExpectation == nil {
		mmGetNumberOfItemInStocks.defaultExpectation = &LomsClientMockGetNumberOfItemInStocksExpectation{}
	}

	mmGetNumberOfItemInStocks.defaultExpectation.params = &LomsClientMockGetNumberOfItemInStocksParams{ctx, skuId}
	for _, e := range mmGetNumberOfItemInStocks.expectations {
		if minimock.Equal(e.params, mmGetNumberOfItemInStocks.defaultExpectation.params) {
			mmGetNumberOfItemInStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetNumberOfItemInStocks.defaultExpectation.params)
		}
	}

	return mmGetNumberOfItemInStocks
}

// Inspect accepts an inspector function that has same arguments as the lomsClient.GetNumberOfItemInStocks
func (mmGetNumberOfItemInStocks *mLomsClientMockGetNumberOfItemInStocks) Inspect(f func(ctx context.Context, skuId int64)) *mLomsClientMockGetNumberOfItemInStocks {
	if mmGetNumberOfItemInStocks.mock.inspectFuncGetNumberOfItemInStocks != nil {
		mmGetNumberOfItemInStocks.mock.t.Fatalf("Inspect function is already set for LomsClientMock.GetNumberOfItemInStocks")
	}

	mmGetNumberOfItemInStocks.mock.inspectFuncGetNumberOfItemInStocks = f

	return mmGetNumberOfItemInStocks
}

// Return sets up results that will be returned by lomsClient.GetNumberOfItemInStocks
func (mmGetNumberOfItemInStocks *mLomsClientMockGetNumberOfItemInStocks) Return(u1 uint64, err error) *LomsClientMock {
	if mmGetNumberOfItemInStocks.mock.funcGetNumberOfItemInStocks != nil {
		mmGetNumberOfItemInStocks.mock.t.Fatalf("LomsClientMock.GetNumberOfItemInStocks mock is already set by Set")
	}

	if mmGetNumberOfItemInStocks.defaultExpectation == nil {
		mmGetNumberOfItemInStocks.defaultExpectation = &LomsClientMockGetNumberOfItemInStocksExpectation{mock: mmGetNumberOfItemInStocks.mock}
	}
	mmGetNumberOfItemInStocks.defaultExpectation.results = &LomsClientMockGetNumberOfItemInStocksResults{u1, err}
	return mmGetNumberOfItemInStocks.mock
}

// Set uses given function f to mock the lomsClient.GetNumberOfItemInStocks method
func (mmGetNumberOfItemInStocks *mLomsClientMockGetNumberOfItemInStocks) Set(f func(ctx context.Context, skuId int64) (u1 uint64, err error)) *LomsClientMock {
	if mmGetNumberOfItemInStocks.defaultExpectation != nil {
		mmGetNumberOfItemInStocks.mock.t.Fatalf("Default expectation is already set for the lomsClient.GetNumberOfItemInStocks method")
	}

	if len(mmGetNumberOfItemInStocks.expectations) > 0 {
		mmGetNumberOfItemInStocks.mock.t.Fatalf("Some expectations are already set for the lomsClient.GetNumberOfItemInStocks method")
	}

	mmGetNumberOfItemInStocks.mock.funcGetNumberOfItemInStocks = f
	return mmGetNumberOfItemInStocks.mock
}

// When sets expectation for the lomsClient.GetNumberOfItemInStocks which will trigger the result defined by the following
// Then helper
func (mmGetNumberOfItemInStocks *mLomsClientMockGetNumberOfItemInStocks) When(ctx context.Context, skuId int64) *LomsClientMockGetNumberOfItemInStocksExpectation {
	if mmGetNumberOfItemInStocks.mock.funcGetNumberOfItemInStocks != nil {
		mmGetNumberOfItemInStocks.mock.t.Fatalf("LomsClientMock.GetNumberOfItemInStocks mock is already set by Set")
	}

	expectation := &LomsClientMockGetNumberOfItemInStocksExpectation{
		mock:   mmGetNumberOfItemInStocks.mock,
		params: &LomsClientMockGetNumberOfItemInStocksParams{ctx, skuId},
	}
	mmGetNumberOfItemInStocks.expectations = append(mmGetNumberOfItemInStocks.expectations, expectation)
	return expectation
}

// Then sets up lomsClient.GetNumberOfItemInStocks return parameters for the expectation previously defined by the When method
func (e *LomsClientMockGetNumberOfItemInStocksExpectation) Then(u1 uint64, err error) *LomsClientMock {
	e.results = &LomsClientMockGetNumberOfItemInStocksResults{u1, err}
	return e.mock
}

// GetNumberOfItemInStocks implements lomsClient
func (mmGetNumberOfItemInStocks *LomsClientMock) GetNumberOfItemInStocks(ctx context.Context, skuId int64) (u1 uint64, err error) {
	mm_atomic.AddUint64(&mmGetNumberOfItemInStocks.beforeGetNumberOfItemInStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmGetNumberOfItemInStocks.afterGetNumberOfItemInStocksCounter, 1)

	if mmGetNumberOfItemInStocks.inspectFuncGetNumberOfItemInStocks != nil {
		mmGetNumberOfItemInStocks.inspectFuncGetNumberOfItemInStocks(ctx, skuId)
	}

	mm_params := LomsClientMockGetNumberOfItemInStocksParams{ctx, skuId}

	// Record call args
	mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.mutex.Lock()
	mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.callArgs = append(mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.callArgs, &mm_params)
	mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.mutex.Unlock()

	for _, e := range mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.defaultExpectation.Counter, 1)
		mm_want := mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.defaultExpectation.params
		mm_got := LomsClientMockGetNumberOfItemInStocksParams{ctx, skuId}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetNumberOfItemInStocks.t.Errorf("LomsClientMock.GetNumberOfItemInStocks got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetNumberOfItemInStocks.GetNumberOfItemInStocksMock.defaultExpectation.results
		if mm_results == nil {
			mmGetNumberOfItemInStocks.t.Fatal("No results are set for the LomsClientMock.GetNumberOfItemInStocks")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmGetNumberOfItemInStocks.funcGetNumberOfItemInStocks != nil {
		return mmGetNumberOfItemInStocks.funcGetNumberOfItemInStocks(ctx, skuId)
	}
	mmGetNumberOfItemInStocks.t.Fatalf("Unexpected call to LomsClientMock.GetNumberOfItemInStocks. %v %v", ctx, skuId)
	return
}

// GetNumberOfItemInStocksAfterCounter returns a count of finished LomsClientMock.GetNumberOfItemInStocks invocations
func (mmGetNumberOfItemInStocks *LomsClientMock) GetNumberOfItemInStocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetNumberOfItemInStocks.afterGetNumberOfItemInStocksCounter)
}

// GetNumberOfItemInStocksBeforeCounter returns a count of LomsClientMock.GetNumberOfItemInStocks invocations
func (mmGetNumberOfItemInStocks *LomsClientMock) GetNumberOfItemInStocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetNumberOfItemInStocks.beforeGetNumberOfItemInStocksCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.GetNumberOfItemInStocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetNumberOfItemInStocks *mLomsClientMockGetNumberOfItemInStocks) Calls() []*LomsClientMockGetNumberOfItemInStocksParams {
	mmGetNumberOfItemInStocks.mutex.RLock()

	argCopy := make([]*LomsClientMockGetNumberOfItemInStocksParams, len(mmGetNumberOfItemInStocks.callArgs))
	copy(argCopy, mmGetNumberOfItemInStocks.callArgs)

	mmGetNumberOfItemInStocks.mutex.RUnlock()

	return argCopy
}

// MinimockGetNumberOfItemInStocksDone returns true if the count of the GetNumberOfItemInStocks invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockGetNumberOfItemInStocksDone() bool {
	for _, e := range m.GetNumberOfItemInStocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetNumberOfItemInStocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetNumberOfItemInStocksCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetNumberOfItemInStocks != nil && mm_atomic.LoadUint64(&m.afterGetNumberOfItemInStocksCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetNumberOfItemInStocksInspect logs each unmet expectation
func (m *LomsClientMock) MinimockGetNumberOfItemInStocksInspect() {
	for _, e := range m.GetNumberOfItemInStocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.GetNumberOfItemInStocks with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetNumberOfItemInStocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetNumberOfItemInStocksCounter) < 1 {
		if m.GetNumberOfItemInStocksMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LomsClientMock.GetNumberOfItemInStocks")
		} else {
			m.t.Errorf("Expected call to LomsClientMock.GetNumberOfItemInStocks with params: %#v", *m.GetNumberOfItemInStocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetNumberOfItemInStocks != nil && mm_atomic.LoadUint64(&m.afterGetNumberOfItemInStocksCounter) < 1 {
		m.t.Error("Expected call to LomsClientMock.GetNumberOfItemInStocks")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateOrderInspect()

			m.MinimockGetNumberOfItemInStocksInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockGetNumberOfItemInStocksDone()
}
