version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    stop_signal: SIGTERM
    depends_on:
      - loms

  loms:
    image: loms
    build: ./loms
    ports:
      - "50051:50051"
      - "8081:8081"
    stop_signal: SIGTERM
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd

  loms-postgres:
    image: postgres:16.2-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd

secrets:
  postgres-passwd:
    file: ./loms/db_password.txt

