version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    stop_signal: SIGTERM
    depends_on:
      - loms

  loms:
    image: loms
    build: ./loms
    ports:
      - "50051:50051"
      - "8081:8081"
    stop_signal: SIGTERM
