version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    stop_signal: SIGTERM
    depends_on:
      loms:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces


  loms:
    image: loms
    build: ./loms
    ports:
      - "50051:50051"
      - "8081:8081"
    stop_signal: SIGTERM
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    secrets:
      - postgres-passwd
    depends_on:
      loms-postgres-master-1:
        condition: service_healthy
      loms-postgres-replica-1:
        condition: service_healthy
      loms-postgres-master-2:
        condition: service_healthy
      loms-postgres-replica-2:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
      jaeger:
        condition: service_started

  loms-postgres-master-1:
    image: postgres:16.2-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  loms-postgres-replica-1:
    image: postgres:16.2-bullseye
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5

  loms-postgres-master-2:
    image: postgres:16.2-bullseye
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  loms-postgres-replica-2:
    image: postgres:16.2-bullseye
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      DYNAMIC_CONFIG_ENABLED: "true"

  kafka0:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka0:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: c5XfbUtrQi6vugAAcm85kQ
    healthcheck:
      test: [ "CMD-SHELL", "cub kafka-ready -b kafka0:29092 1 30" ]
      interval: 1s
      timeout: 10s
      retries: 5

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      kafka0:
        condition: service_healthy
    command: "kafka-topics --create --topic loms.order-events --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:29092"

  notifier:
    image: notifier
    build: ./notifier
    deploy:
      replicas: 3
    stop_signal: SIGTERM
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
      jaeger:
        condition: service_started
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces

  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686"
      - "4318:4318"
  prometheus:
    image: prom/prometheus:v2.51.2
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources/


secrets:
  postgres-passwd:
    file: ./loms/db_password.txt

