// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package stocks

import (
	"context"
)

const selectCount = `-- name: selectCount :one
SELECT total, reserved
FROM item_unit
WHERE sku_id = $1
`

type selectCountRow struct {
	Total    int32
	Reserved int32
}

func (q *Queries) selectCount(ctx context.Context, skuID int64) (selectCountRow, error) {
	row := q.db.QueryRow(ctx, selectCount, skuID)
	var i selectCountRow
	err := row.Scan(&i.Total, &i.Reserved)
	return i, err
}
