{
 "title": "Cache",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hit ratio",
   "type": "timeseries",
   "description": "hit ratio кеша",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cart_cache_hit_seconds_count / (cart_cache_hit_seconds_count + cart_cache_miss_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache miss duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "cart_cache_miss_seconds{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "cart_cache_hit_seconds{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}