// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package orderscanceller

//go:generate minimock -i route256.ozon.ru/project/loms/internal/usecases/orderscanceller.StockRepo -o stock_repo_mock_test.go -n StockRepoMock -p orderscanceller

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/loms/internal/models"
)

// StockRepoMock implements StockRepo
type StockRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddItems          func(ctx context.Context, oa1 []models.OrderItem) (err error)
	inspectFuncAddItems   func(ctx context.Context, oa1 []models.OrderItem)
	afterAddItemsCounter  uint64
	beforeAddItemsCounter uint64
	AddItemsMock          mStockRepoMockAddItems

	funcCancelReserved          func(ctx context.Context, oa1 []models.OrderItem) (err error)
	inspectFuncCancelReserved   func(ctx context.Context, oa1 []models.OrderItem)
	afterCancelReservedCounter  uint64
	beforeCancelReservedCounter uint64
	CancelReservedMock          mStockRepoMockCancelReserved
}

// NewStockRepoMock returns a mock for StockRepo
func NewStockRepoMock(t minimock.Tester) *StockRepoMock {
	m := &StockRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddItemsMock = mStockRepoMockAddItems{mock: m}
	m.AddItemsMock.callArgs = []*StockRepoMockAddItemsParams{}

	m.CancelReservedMock = mStockRepoMockCancelReserved{mock: m}
	m.CancelReservedMock.callArgs = []*StockRepoMockCancelReservedParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStockRepoMockAddItems struct {
	mock               *StockRepoMock
	defaultExpectation *StockRepoMockAddItemsExpectation
	expectations       []*StockRepoMockAddItemsExpectation

	callArgs []*StockRepoMockAddItemsParams
	mutex    sync.RWMutex
}

// StockRepoMockAddItemsExpectation specifies expectation struct of the StockRepo.AddItems
type StockRepoMockAddItemsExpectation struct {
	mock    *StockRepoMock
	params  *StockRepoMockAddItemsParams
	results *StockRepoMockAddItemsResults
	Counter uint64
}

// StockRepoMockAddItemsParams contains parameters of the StockRepo.AddItems
type StockRepoMockAddItemsParams struct {
	ctx context.Context
	oa1 []models.OrderItem
}

// StockRepoMockAddItemsResults contains results of the StockRepo.AddItems
type StockRepoMockAddItemsResults struct {
	err error
}

// Expect sets up expected params for StockRepo.AddItems
func (mmAddItems *mStockRepoMockAddItems) Expect(ctx context.Context, oa1 []models.OrderItem) *mStockRepoMockAddItems {
	if mmAddItems.mock.funcAddItems != nil {
		mmAddItems.mock.t.Fatalf("StockRepoMock.AddItems mock is already set by Set")
	}

	if mmAddItems.defaultExpectation == nil {
		mmAddItems.defaultExpectation = &StockRepoMockAddItemsExpectation{}
	}

	mmAddItems.defaultExpectation.params = &StockRepoMockAddItemsParams{ctx, oa1}
	for _, e := range mmAddItems.expectations {
		if minimock.Equal(e.params, mmAddItems.defaultExpectation.params) {
			mmAddItems.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddItems.defaultExpectation.params)
		}
	}

	return mmAddItems
}

// Inspect accepts an inspector function that has same arguments as the StockRepo.AddItems
func (mmAddItems *mStockRepoMockAddItems) Inspect(f func(ctx context.Context, oa1 []models.OrderItem)) *mStockRepoMockAddItems {
	if mmAddItems.mock.inspectFuncAddItems != nil {
		mmAddItems.mock.t.Fatalf("Inspect function is already set for StockRepoMock.AddItems")
	}

	mmAddItems.mock.inspectFuncAddItems = f

	return mmAddItems
}

// Return sets up results that will be returned by StockRepo.AddItems
func (mmAddItems *mStockRepoMockAddItems) Return(err error) *StockRepoMock {
	if mmAddItems.mock.funcAddItems != nil {
		mmAddItems.mock.t.Fatalf("StockRepoMock.AddItems mock is already set by Set")
	}

	if mmAddItems.defaultExpectation == nil {
		mmAddItems.defaultExpectation = &StockRepoMockAddItemsExpectation{mock: mmAddItems.mock}
	}
	mmAddItems.defaultExpectation.results = &StockRepoMockAddItemsResults{err}
	return mmAddItems.mock
}

// Set uses given function f to mock the StockRepo.AddItems method
func (mmAddItems *mStockRepoMockAddItems) Set(f func(ctx context.Context, oa1 []models.OrderItem) (err error)) *StockRepoMock {
	if mmAddItems.defaultExpectation != nil {
		mmAddItems.mock.t.Fatalf("Default expectation is already set for the StockRepo.AddItems method")
	}

	if len(mmAddItems.expectations) > 0 {
		mmAddItems.mock.t.Fatalf("Some expectations are already set for the StockRepo.AddItems method")
	}

	mmAddItems.mock.funcAddItems = f
	return mmAddItems.mock
}

// When sets expectation for the StockRepo.AddItems which will trigger the result defined by the following
// Then helper
func (mmAddItems *mStockRepoMockAddItems) When(ctx context.Context, oa1 []models.OrderItem) *StockRepoMockAddItemsExpectation {
	if mmAddItems.mock.funcAddItems != nil {
		mmAddItems.mock.t.Fatalf("StockRepoMock.AddItems mock is already set by Set")
	}

	expectation := &StockRepoMockAddItemsExpectation{
		mock:   mmAddItems.mock,
		params: &StockRepoMockAddItemsParams{ctx, oa1},
	}
	mmAddItems.expectations = append(mmAddItems.expectations, expectation)
	return expectation
}

// Then sets up StockRepo.AddItems return parameters for the expectation previously defined by the When method
func (e *StockRepoMockAddItemsExpectation) Then(err error) *StockRepoMock {
	e.results = &StockRepoMockAddItemsResults{err}
	return e.mock
}

// AddItems implements StockRepo
func (mmAddItems *StockRepoMock) AddItems(ctx context.Context, oa1 []models.OrderItem) (err error) {
	mm_atomic.AddUint64(&mmAddItems.beforeAddItemsCounter, 1)
	defer mm_atomic.AddUint64(&mmAddItems.afterAddItemsCounter, 1)

	if mmAddItems.inspectFuncAddItems != nil {
		mmAddItems.inspectFuncAddItems(ctx, oa1)
	}

	mm_params := StockRepoMockAddItemsParams{ctx, oa1}

	// Record call args
	mmAddItems.AddItemsMock.mutex.Lock()
	mmAddItems.AddItemsMock.callArgs = append(mmAddItems.AddItemsMock.callArgs, &mm_params)
	mmAddItems.AddItemsMock.mutex.Unlock()

	for _, e := range mmAddItems.AddItemsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddItems.AddItemsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddItems.AddItemsMock.defaultExpectation.Counter, 1)
		mm_want := mmAddItems.AddItemsMock.defaultExpectation.params
		mm_got := StockRepoMockAddItemsParams{ctx, oa1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddItems.t.Errorf("StockRepoMock.AddItems got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddItems.AddItemsMock.defaultExpectation.results
		if mm_results == nil {
			mmAddItems.t.Fatal("No results are set for the StockRepoMock.AddItems")
		}
		return (*mm_results).err
	}
	if mmAddItems.funcAddItems != nil {
		return mmAddItems.funcAddItems(ctx, oa1)
	}
	mmAddItems.t.Fatalf("Unexpected call to StockRepoMock.AddItems. %v %v", ctx, oa1)
	return
}

// AddItemsAfterCounter returns a count of finished StockRepoMock.AddItems invocations
func (mmAddItems *StockRepoMock) AddItemsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItems.afterAddItemsCounter)
}

// AddItemsBeforeCounter returns a count of StockRepoMock.AddItems invocations
func (mmAddItems *StockRepoMock) AddItemsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItems.beforeAddItemsCounter)
}

// Calls returns a list of arguments used in each call to StockRepoMock.AddItems.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddItems *mStockRepoMockAddItems) Calls() []*StockRepoMockAddItemsParams {
	mmAddItems.mutex.RLock()

	argCopy := make([]*StockRepoMockAddItemsParams, len(mmAddItems.callArgs))
	copy(argCopy, mmAddItems.callArgs)

	mmAddItems.mutex.RUnlock()

	return argCopy
}

// MinimockAddItemsDone returns true if the count of the AddItems invocations corresponds
// the number of defined expectations
func (m *StockRepoMock) MinimockAddItemsDone() bool {
	for _, e := range m.AddItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddItemsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItems != nil && mm_atomic.LoadUint64(&m.afterAddItemsCounter) < 1 {
		return false
	}
	return true
}

// MinimockAddItemsInspect logs each unmet expectation
func (m *StockRepoMock) MinimockAddItemsInspect() {
	for _, e := range m.AddItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StockRepoMock.AddItems with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddItemsCounter) < 1 {
		if m.AddItemsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StockRepoMock.AddItems")
		} else {
			m.t.Errorf("Expected call to StockRepoMock.AddItems with params: %#v", *m.AddItemsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItems != nil && mm_atomic.LoadUint64(&m.afterAddItemsCounter) < 1 {
		m.t.Error("Expected call to StockRepoMock.AddItems")
	}
}

type mStockRepoMockCancelReserved struct {
	mock               *StockRepoMock
	defaultExpectation *StockRepoMockCancelReservedExpectation
	expectations       []*StockRepoMockCancelReservedExpectation

	callArgs []*StockRepoMockCancelReservedParams
	mutex    sync.RWMutex
}

// StockRepoMockCancelReservedExpectation specifies expectation struct of the StockRepo.CancelReserved
type StockRepoMockCancelReservedExpectation struct {
	mock    *StockRepoMock
	params  *StockRepoMockCancelReservedParams
	results *StockRepoMockCancelReservedResults
	Counter uint64
}

// StockRepoMockCancelReservedParams contains parameters of the StockRepo.CancelReserved
type StockRepoMockCancelReservedParams struct {
	ctx context.Context
	oa1 []models.OrderItem
}

// StockRepoMockCancelReservedResults contains results of the StockRepo.CancelReserved
type StockRepoMockCancelReservedResults struct {
	err error
}

// Expect sets up expected params for StockRepo.CancelReserved
func (mmCancelReserved *mStockRepoMockCancelReserved) Expect(ctx context.Context, oa1 []models.OrderItem) *mStockRepoMockCancelReserved {
	if mmCancelReserved.mock.funcCancelReserved != nil {
		mmCancelReserved.mock.t.Fatalf("StockRepoMock.CancelReserved mock is already set by Set")
	}

	if mmCancelReserved.defaultExpectation == nil {
		mmCancelReserved.defaultExpectation = &StockRepoMockCancelReservedExpectation{}
	}

	mmCancelReserved.defaultExpectation.params = &StockRepoMockCancelReservedParams{ctx, oa1}
	for _, e := range mmCancelReserved.expectations {
		if minimock.Equal(e.params, mmCancelReserved.defaultExpectation.params) {
			mmCancelReserved.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCancelReserved.defaultExpectation.params)
		}
	}

	return mmCancelReserved
}

// Inspect accepts an inspector function that has same arguments as the StockRepo.CancelReserved
func (mmCancelReserved *mStockRepoMockCancelReserved) Inspect(f func(ctx context.Context, oa1 []models.OrderItem)) *mStockRepoMockCancelReserved {
	if mmCancelReserved.mock.inspectFuncCancelReserved != nil {
		mmCancelReserved.mock.t.Fatalf("Inspect function is already set for StockRepoMock.CancelReserved")
	}

	mmCancelReserved.mock.inspectFuncCancelReserved = f

	return mmCancelReserved
}

// Return sets up results that will be returned by StockRepo.CancelReserved
func (mmCancelReserved *mStockRepoMockCancelReserved) Return(err error) *StockRepoMock {
	if mmCancelReserved.mock.funcCancelReserved != nil {
		mmCancelReserved.mock.t.Fatalf("StockRepoMock.CancelReserved mock is already set by Set")
	}

	if mmCancelReserved.defaultExpectation == nil {
		mmCancelReserved.defaultExpectation = &StockRepoMockCancelReservedExpectation{mock: mmCancelReserved.mock}
	}
	mmCancelReserved.defaultExpectation.results = &StockRepoMockCancelReservedResults{err}
	return mmCancelReserved.mock
}

// Set uses given function f to mock the StockRepo.CancelReserved method
func (mmCancelReserved *mStockRepoMockCancelReserved) Set(f func(ctx context.Context, oa1 []models.OrderItem) (err error)) *StockRepoMock {
	if mmCancelReserved.defaultExpectation != nil {
		mmCancelReserved.mock.t.Fatalf("Default expectation is already set for the StockRepo.CancelReserved method")
	}

	if len(mmCancelReserved.expectations) > 0 {
		mmCancelReserved.mock.t.Fatalf("Some expectations are already set for the StockRepo.CancelReserved method")
	}

	mmCancelReserved.mock.funcCancelReserved = f
	return mmCancelReserved.mock
}

// When sets expectation for the StockRepo.CancelReserved which will trigger the result defined by the following
// Then helper
func (mmCancelReserved *mStockRepoMockCancelReserved) When(ctx context.Context, oa1 []models.OrderItem) *StockRepoMockCancelReservedExpectation {
	if mmCancelReserved.mock.funcCancelReserved != nil {
		mmCancelReserved.mock.t.Fatalf("StockRepoMock.CancelReserved mock is already set by Set")
	}

	expectation := &StockRepoMockCancelReservedExpectation{
		mock:   mmCancelReserved.mock,
		params: &StockRepoMockCancelReservedParams{ctx, oa1},
	}
	mmCancelReserved.expectations = append(mmCancelReserved.expectations, expectation)
	return expectation
}

// Then sets up StockRepo.CancelReserved return parameters for the expectation previously defined by the When method
func (e *StockRepoMockCancelReservedExpectation) Then(err error) *StockRepoMock {
	e.results = &StockRepoMockCancelReservedResults{err}
	return e.mock
}

// CancelReserved implements StockRepo
func (mmCancelReserved *StockRepoMock) CancelReserved(ctx context.Context, oa1 []models.OrderItem) (err error) {
	mm_atomic.AddUint64(&mmCancelReserved.beforeCancelReservedCounter, 1)
	defer mm_atomic.AddUint64(&mmCancelReserved.afterCancelReservedCounter, 1)

	if mmCancelReserved.inspectFuncCancelReserved != nil {
		mmCancelReserved.inspectFuncCancelReserved(ctx, oa1)
	}

	mm_params := StockRepoMockCancelReservedParams{ctx, oa1}

	// Record call args
	mmCancelReserved.CancelReservedMock.mutex.Lock()
	mmCancelReserved.CancelReservedMock.callArgs = append(mmCancelReserved.CancelReservedMock.callArgs, &mm_params)
	mmCancelReserved.CancelReservedMock.mutex.Unlock()

	for _, e := range mmCancelReserved.CancelReservedMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCancelReserved.CancelReservedMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCancelReserved.CancelReservedMock.defaultExpectation.Counter, 1)
		mm_want := mmCancelReserved.CancelReservedMock.defaultExpectation.params
		mm_got := StockRepoMockCancelReservedParams{ctx, oa1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCancelReserved.t.Errorf("StockRepoMock.CancelReserved got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCancelReserved.CancelReservedMock.defaultExpectation.results
		if mm_results == nil {
			mmCancelReserved.t.Fatal("No results are set for the StockRepoMock.CancelReserved")
		}
		return (*mm_results).err
	}
	if mmCancelReserved.funcCancelReserved != nil {
		return mmCancelReserved.funcCancelReserved(ctx, oa1)
	}
	mmCancelReserved.t.Fatalf("Unexpected call to StockRepoMock.CancelReserved. %v %v", ctx, oa1)
	return
}

// CancelReservedAfterCounter returns a count of finished StockRepoMock.CancelReserved invocations
func (mmCancelReserved *StockRepoMock) CancelReservedAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelReserved.afterCancelReservedCounter)
}

// CancelReservedBeforeCounter returns a count of StockRepoMock.CancelReserved invocations
func (mmCancelReserved *StockRepoMock) CancelReservedBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelReserved.beforeCancelReservedCounter)
}

// Calls returns a list of arguments used in each call to StockRepoMock.CancelReserved.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCancelReserved *mStockRepoMockCancelReserved) Calls() []*StockRepoMockCancelReservedParams {
	mmCancelReserved.mutex.RLock()

	argCopy := make([]*StockRepoMockCancelReservedParams, len(mmCancelReserved.callArgs))
	copy(argCopy, mmCancelReserved.callArgs)

	mmCancelReserved.mutex.RUnlock()

	return argCopy
}

// MinimockCancelReservedDone returns true if the count of the CancelReserved invocations corresponds
// the number of defined expectations
func (m *StockRepoMock) MinimockCancelReservedDone() bool {
	for _, e := range m.CancelReservedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CancelReservedMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCancelReservedCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCancelReserved != nil && mm_atomic.LoadUint64(&m.afterCancelReservedCounter) < 1 {
		return false
	}
	return true
}

// MinimockCancelReservedInspect logs each unmet expectation
func (m *StockRepoMock) MinimockCancelReservedInspect() {
	for _, e := range m.CancelReservedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StockRepoMock.CancelReserved with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CancelReservedMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCancelReservedCounter) < 1 {
		if m.CancelReservedMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StockRepoMock.CancelReserved")
		} else {
			m.t.Errorf("Expected call to StockRepoMock.CancelReserved with params: %#v", *m.CancelReservedMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCancelReserved != nil && mm_atomic.LoadUint64(&m.afterCancelReservedCounter) < 1 {
		m.t.Error("Expected call to StockRepoMock.CancelReserved")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StockRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddItemsInspect()

			m.MinimockCancelReservedInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StockRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StockRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddItemsDone() &&
		m.MinimockCancelReservedDone()
}
