// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package lister

//go:generate minimock -i route256.ozon.ru/project/cart/internal/usecases/lister.repository -o repository_mock_test.go -n RepositoryMock -p lister

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/cart/internal/models"
)

// RepositoryMock implements repository
type RepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetCart          func(ctx context.Context, user int64) (cp1 *models.Cart, err error)
	inspectFuncGetCart   func(ctx context.Context, user int64)
	afterGetCartCounter  uint64
	beforeGetCartCounter uint64
	GetCartMock          mRepositoryMockGetCart
}

// NewRepositoryMock returns a mock for repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetCartMock = mRepositoryMockGetCart{mock: m}
	m.GetCartMock.callArgs = []*RepositoryMockGetCartParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepositoryMockGetCart struct {
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockGetCartExpectation
	expectations       []*RepositoryMockGetCartExpectation

	callArgs []*RepositoryMockGetCartParams
	mutex    sync.RWMutex
}

// RepositoryMockGetCartExpectation specifies expectation struct of the repository.GetCart
type RepositoryMockGetCartExpectation struct {
	mock    *RepositoryMock
	params  *RepositoryMockGetCartParams
	results *RepositoryMockGetCartResults
	Counter uint64
}

// RepositoryMockGetCartParams contains parameters of the repository.GetCart
type RepositoryMockGetCartParams struct {
	ctx  context.Context
	user int64
}

// RepositoryMockGetCartResults contains results of the repository.GetCart
type RepositoryMockGetCartResults struct {
	cp1 *models.Cart
	err error
}

// Expect sets up expected params for repository.GetCart
func (mmGetCart *mRepositoryMockGetCart) Expect(ctx context.Context, user int64) *mRepositoryMockGetCart {
	if mmGetCart.mock.funcGetCart != nil {
		mmGetCart.mock.t.Fatalf("RepositoryMock.GetCart mock is already set by Set")
	}

	if mmGetCart.defaultExpectation == nil {
		mmGetCart.defaultExpectation = &RepositoryMockGetCartExpectation{}
	}

	mmGetCart.defaultExpectation.params = &RepositoryMockGetCartParams{ctx, user}
	for _, e := range mmGetCart.expectations {
		if minimock.Equal(e.params, mmGetCart.defaultExpectation.params) {
			mmGetCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetCart.defaultExpectation.params)
		}
	}

	return mmGetCart
}

// Inspect accepts an inspector function that has same arguments as the repository.GetCart
func (mmGetCart *mRepositoryMockGetCart) Inspect(f func(ctx context.Context, user int64)) *mRepositoryMockGetCart {
	if mmGetCart.mock.inspectFuncGetCart != nil {
		mmGetCart.mock.t.Fatalf("Inspect function is already set for RepositoryMock.GetCart")
	}

	mmGetCart.mock.inspectFuncGetCart = f

	return mmGetCart
}

// Return sets up results that will be returned by repository.GetCart
func (mmGetCart *mRepositoryMockGetCart) Return(cp1 *models.Cart, err error) *RepositoryMock {
	if mmGetCart.mock.funcGetCart != nil {
		mmGetCart.mock.t.Fatalf("RepositoryMock.GetCart mock is already set by Set")
	}

	if mmGetCart.defaultExpectation == nil {
		mmGetCart.defaultExpectation = &RepositoryMockGetCartExpectation{mock: mmGetCart.mock}
	}
	mmGetCart.defaultExpectation.results = &RepositoryMockGetCartResults{cp1, err}
	return mmGetCart.mock
}

// Set uses given function f to mock the repository.GetCart method
func (mmGetCart *mRepositoryMockGetCart) Set(f func(ctx context.Context, user int64) (cp1 *models.Cart, err error)) *RepositoryMock {
	if mmGetCart.defaultExpectation != nil {
		mmGetCart.mock.t.Fatalf("Default expectation is already set for the repository.GetCart method")
	}

	if len(mmGetCart.expectations) > 0 {
		mmGetCart.mock.t.Fatalf("Some expectations are already set for the repository.GetCart method")
	}

	mmGetCart.mock.funcGetCart = f
	return mmGetCart.mock
}

// When sets expectation for the repository.GetCart which will trigger the result defined by the following
// Then helper
func (mmGetCart *mRepositoryMockGetCart) When(ctx context.Context, user int64) *RepositoryMockGetCartExpectation {
	if mmGetCart.mock.funcGetCart != nil {
		mmGetCart.mock.t.Fatalf("RepositoryMock.GetCart mock is already set by Set")
	}

	expectation := &RepositoryMockGetCartExpectation{
		mock:   mmGetCart.mock,
		params: &RepositoryMockGetCartParams{ctx, user},
	}
	mmGetCart.expectations = append(mmGetCart.expectations, expectation)
	return expectation
}

// Then sets up repository.GetCart return parameters for the expectation previously defined by the When method
func (e *RepositoryMockGetCartExpectation) Then(cp1 *models.Cart, err error) *RepositoryMock {
	e.results = &RepositoryMockGetCartResults{cp1, err}
	return e.mock
}

// GetCart implements repository
func (mmGetCart *RepositoryMock) GetCart(ctx context.Context, user int64) (cp1 *models.Cart, err error) {
	mm_atomic.AddUint64(&mmGetCart.beforeGetCartCounter, 1)
	defer mm_atomic.AddUint64(&mmGetCart.afterGetCartCounter, 1)

	if mmGetCart.inspectFuncGetCart != nil {
		mmGetCart.inspectFuncGetCart(ctx, user)
	}

	mm_params := RepositoryMockGetCartParams{ctx, user}

	// Record call args
	mmGetCart.GetCartMock.mutex.Lock()
	mmGetCart.GetCartMock.callArgs = append(mmGetCart.GetCartMock.callArgs, &mm_params)
	mmGetCart.GetCartMock.mutex.Unlock()

	for _, e := range mmGetCart.GetCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetCart.GetCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetCart.GetCartMock.defaultExpectation.Counter, 1)
		mm_want := mmGetCart.GetCartMock.defaultExpectation.params
		mm_got := RepositoryMockGetCartParams{ctx, user}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetCart.t.Errorf("RepositoryMock.GetCart got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetCart.GetCartMock.defaultExpectation.results
		if mm_results == nil {
			mmGetCart.t.Fatal("No results are set for the RepositoryMock.GetCart")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetCart.funcGetCart != nil {
		return mmGetCart.funcGetCart(ctx, user)
	}
	mmGetCart.t.Fatalf("Unexpected call to RepositoryMock.GetCart. %v %v", ctx, user)
	return
}

// GetCartAfterCounter returns a count of finished RepositoryMock.GetCart invocations
func (mmGetCart *RepositoryMock) GetCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCart.afterGetCartCounter)
}

// GetCartBeforeCounter returns a count of RepositoryMock.GetCart invocations
func (mmGetCart *RepositoryMock) GetCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCart.beforeGetCartCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.GetCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetCart *mRepositoryMockGetCart) Calls() []*RepositoryMockGetCartParams {
	mmGetCart.mutex.RLock()

	argCopy := make([]*RepositoryMockGetCartParams, len(mmGetCart.callArgs))
	copy(argCopy, mmGetCart.callArgs)

	mmGetCart.mutex.RUnlock()

	return argCopy
}

// MinimockGetCartDone returns true if the count of the GetCart invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockGetCartDone() bool {
	for _, e := range m.GetCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetCartMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCartCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCart != nil && mm_atomic.LoadUint64(&m.afterGetCartCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetCartInspect logs each unmet expectation
func (m *RepositoryMock) MinimockGetCartInspect() {
	for _, e := range m.GetCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.GetCart with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetCartMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCartCounter) < 1 {
		if m.GetCartMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepositoryMock.GetCart")
		} else {
			m.t.Errorf("Expected call to RepositoryMock.GetCart with params: %#v", *m.GetCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCart != nil && mm_atomic.LoadUint64(&m.afterGetCartCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.GetCart")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetCartInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetCartDone()
}
