// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package retriablehttp

//go:generate minimock -i net/http.RoundTripper -o round_tripper_mock_test.go -n HttpRoundTripper -p client

import (
	mm_http "net/http"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// HttpRoundTripper implements http.RoundTripper
type HttpRoundTripper struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRoundTrip          func(rp1 *mm_http.Request) (rp2 *mm_http.Response, err error)
	inspectFuncRoundTrip   func(rp1 *mm_http.Request)
	afterRoundTripCounter  uint64
	beforeRoundTripCounter uint64
	RoundTripMock          mHttpRoundTripperRoundTrip
}

// NewHttpRoundTripper returns a mock for http.RoundTripper
func NewHttpRoundTripper(t minimock.Tester) *HttpRoundTripper {
	m := &HttpRoundTripper{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RoundTripMock = mHttpRoundTripperRoundTrip{mock: m}
	m.RoundTripMock.callArgs = []*HttpRoundTripperRoundTripParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mHttpRoundTripperRoundTrip struct {
	mock               *HttpRoundTripper
	defaultExpectation *HttpRoundTripperRoundTripExpectation
	expectations       []*HttpRoundTripperRoundTripExpectation

	callArgs []*HttpRoundTripperRoundTripParams
	mutex    sync.RWMutex
}

// HttpRoundTripperRoundTripExpectation specifies expectation struct of the RoundTripper.RoundTrip
type HttpRoundTripperRoundTripExpectation struct {
	mock    *HttpRoundTripper
	params  *HttpRoundTripperRoundTripParams
	results *HttpRoundTripperRoundTripResults
	Counter uint64
}

// HttpRoundTripperRoundTripParams contains parameters of the RoundTripper.RoundTrip
type HttpRoundTripperRoundTripParams struct {
	rp1 *mm_http.Request
}

// HttpRoundTripperRoundTripResults contains results of the RoundTripper.RoundTrip
type HttpRoundTripperRoundTripResults struct {
	rp2 *mm_http.Response
	err error
}

// Expect sets up expected params for RoundTripper.RoundTrip
func (mmRoundTrip *mHttpRoundTripperRoundTrip) Expect(rp1 *mm_http.Request) *mHttpRoundTripperRoundTrip {
	if mmRoundTrip.mock.funcRoundTrip != nil {
		mmRoundTrip.mock.t.Fatalf("HttpRoundTripper.RoundTrip mock is already set by Set")
	}

	if mmRoundTrip.defaultExpectation == nil {
		mmRoundTrip.defaultExpectation = &HttpRoundTripperRoundTripExpectation{}
	}

	mmRoundTrip.defaultExpectation.params = &HttpRoundTripperRoundTripParams{rp1}
	for _, e := range mmRoundTrip.expectations {
		if minimock.Equal(e.params, mmRoundTrip.defaultExpectation.params) {
			mmRoundTrip.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRoundTrip.defaultExpectation.params)
		}
	}

	return mmRoundTrip
}

// Inspect accepts an inspector function that has same arguments as the RoundTripper.RoundTrip
func (mmRoundTrip *mHttpRoundTripperRoundTrip) Inspect(f func(rp1 *mm_http.Request)) *mHttpRoundTripperRoundTrip {
	if mmRoundTrip.mock.inspectFuncRoundTrip != nil {
		mmRoundTrip.mock.t.Fatalf("Inspect function is already set for HttpRoundTripper.RoundTrip")
	}

	mmRoundTrip.mock.inspectFuncRoundTrip = f

	return mmRoundTrip
}

// Return sets up results that will be returned by RoundTripper.RoundTrip
func (mmRoundTrip *mHttpRoundTripperRoundTrip) Return(rp2 *mm_http.Response, err error) *HttpRoundTripper {
	if mmRoundTrip.mock.funcRoundTrip != nil {
		mmRoundTrip.mock.t.Fatalf("HttpRoundTripper.RoundTrip mock is already set by Set")
	}

	if mmRoundTrip.defaultExpectation == nil {
		mmRoundTrip.defaultExpectation = &HttpRoundTripperRoundTripExpectation{mock: mmRoundTrip.mock}
	}
	mmRoundTrip.defaultExpectation.results = &HttpRoundTripperRoundTripResults{rp2, err}
	return mmRoundTrip.mock
}

// Set uses given function f to mock the RoundTripper.RoundTrip method
func (mmRoundTrip *mHttpRoundTripperRoundTrip) Set(f func(rp1 *mm_http.Request) (rp2 *mm_http.Response, err error)) *HttpRoundTripper {
	if mmRoundTrip.defaultExpectation != nil {
		mmRoundTrip.mock.t.Fatalf("Default expectation is already set for the RoundTripper.RoundTrip method")
	}

	if len(mmRoundTrip.expectations) > 0 {
		mmRoundTrip.mock.t.Fatalf("Some expectations are already set for the RoundTripper.RoundTrip method")
	}

	mmRoundTrip.mock.funcRoundTrip = f
	return mmRoundTrip.mock
}

// When sets expectation for the RoundTripper.RoundTrip which will trigger the result defined by the following
// Then helper
func (mmRoundTrip *mHttpRoundTripperRoundTrip) When(rp1 *mm_http.Request) *HttpRoundTripperRoundTripExpectation {
	if mmRoundTrip.mock.funcRoundTrip != nil {
		mmRoundTrip.mock.t.Fatalf("HttpRoundTripper.RoundTrip mock is already set by Set")
	}

	expectation := &HttpRoundTripperRoundTripExpectation{
		mock:   mmRoundTrip.mock,
		params: &HttpRoundTripperRoundTripParams{rp1},
	}
	mmRoundTrip.expectations = append(mmRoundTrip.expectations, expectation)
	return expectation
}

// Then sets up RoundTripper.RoundTrip return parameters for the expectation previously defined by the When method
func (e *HttpRoundTripperRoundTripExpectation) Then(rp2 *mm_http.Response, err error) *HttpRoundTripper {
	e.results = &HttpRoundTripperRoundTripResults{rp2, err}
	return e.mock
}

// RoundTrip implements http.RoundTripper
func (mmRoundTrip *HttpRoundTripper) RoundTrip(rp1 *mm_http.Request) (rp2 *mm_http.Response, err error) {
	mm_atomic.AddUint64(&mmRoundTrip.beforeRoundTripCounter, 1)
	defer mm_atomic.AddUint64(&mmRoundTrip.afterRoundTripCounter, 1)

	if mmRoundTrip.inspectFuncRoundTrip != nil {
		mmRoundTrip.inspectFuncRoundTrip(rp1)
	}

	mm_params := HttpRoundTripperRoundTripParams{rp1}

	// Record call args
	mmRoundTrip.RoundTripMock.mutex.Lock()
	mmRoundTrip.RoundTripMock.callArgs = append(mmRoundTrip.RoundTripMock.callArgs, &mm_params)
	mmRoundTrip.RoundTripMock.mutex.Unlock()

	for _, e := range mmRoundTrip.RoundTripMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp2, e.results.err
		}
	}

	if mmRoundTrip.RoundTripMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRoundTrip.RoundTripMock.defaultExpectation.Counter, 1)
		mm_want := mmRoundTrip.RoundTripMock.defaultExpectation.params
		mm_got := HttpRoundTripperRoundTripParams{rp1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRoundTrip.t.Errorf("HttpRoundTripper.RoundTrip got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRoundTrip.RoundTripMock.defaultExpectation.results
		if mm_results == nil {
			mmRoundTrip.t.Fatal("No results are set for the HttpRoundTripper.RoundTrip")
		}
		return (*mm_results).rp2, (*mm_results).err
	}
	if mmRoundTrip.funcRoundTrip != nil {
		return mmRoundTrip.funcRoundTrip(rp1)
	}
	mmRoundTrip.t.Fatalf("Unexpected call to HttpRoundTripper.RoundTrip. %v", rp1)
	return
}

// RoundTripAfterCounter returns a count of finished HttpRoundTripper.RoundTrip invocations
func (mmRoundTrip *HttpRoundTripper) RoundTripAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRoundTrip.afterRoundTripCounter)
}

// RoundTripBeforeCounter returns a count of HttpRoundTripper.RoundTrip invocations
func (mmRoundTrip *HttpRoundTripper) RoundTripBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRoundTrip.beforeRoundTripCounter)
}

// Calls returns a list of arguments used in each call to HttpRoundTripper.RoundTrip.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRoundTrip *mHttpRoundTripperRoundTrip) Calls() []*HttpRoundTripperRoundTripParams {
	mmRoundTrip.mutex.RLock()

	argCopy := make([]*HttpRoundTripperRoundTripParams, len(mmRoundTrip.callArgs))
	copy(argCopy, mmRoundTrip.callArgs)

	mmRoundTrip.mutex.RUnlock()

	return argCopy
}

// MinimockRoundTripDone returns true if the count of the RoundTrip invocations corresponds
// the number of defined expectations
func (m *HttpRoundTripper) MinimockRoundTripDone() bool {
	for _, e := range m.RoundTripMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RoundTripMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRoundTripCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRoundTrip != nil && mm_atomic.LoadUint64(&m.afterRoundTripCounter) < 1 {
		return false
	}
	return true
}

// MinimockRoundTripInspect logs each unmet expectation
func (m *HttpRoundTripper) MinimockRoundTripInspect() {
	for _, e := range m.RoundTripMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to HttpRoundTripper.RoundTrip with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RoundTripMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRoundTripCounter) < 1 {
		if m.RoundTripMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to HttpRoundTripper.RoundTrip")
		} else {
			m.t.Errorf("Expected call to HttpRoundTripper.RoundTrip with params: %#v", *m.RoundTripMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRoundTrip != nil && mm_atomic.LoadUint64(&m.afterRoundTripCounter) < 1 {
		m.t.Error("Expected call to HttpRoundTripper.RoundTrip")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *HttpRoundTripper) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRoundTripInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *HttpRoundTripper) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *HttpRoundTripper) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRoundTripDone()
}
