// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package orderscreator

//go:generate minimock -i route256.ozon.ru/project/loms/internal/usecases/orderscreator.OrderRepo -o order_repo_mock_test.go -n OrderRepoMock -p orderscreator

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/loms/internal/models"
)

// OrderRepoMock implements OrderRepo
type OrderRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, i1 int64, oa1 []models.OrderItem) (op1 *models.Order, err error)
	inspectFuncCreate   func(ctx context.Context, i1 int64, oa1 []models.OrderItem)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mOrderRepoMockCreate

	funcSave          func(ctx context.Context, op1 *models.Order) (err error)
	inspectFuncSave   func(ctx context.Context, op1 *models.Order)
	afterSaveCounter  uint64
	beforeSaveCounter uint64
	SaveMock          mOrderRepoMockSave
}

// NewOrderRepoMock returns a mock for OrderRepo
func NewOrderRepoMock(t minimock.Tester) *OrderRepoMock {
	m := &OrderRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mOrderRepoMockCreate{mock: m}
	m.CreateMock.callArgs = []*OrderRepoMockCreateParams{}

	m.SaveMock = mOrderRepoMockSave{mock: m}
	m.SaveMock.callArgs = []*OrderRepoMockSaveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderRepoMockCreate struct {
	mock               *OrderRepoMock
	defaultExpectation *OrderRepoMockCreateExpectation
	expectations       []*OrderRepoMockCreateExpectation

	callArgs []*OrderRepoMockCreateParams
	mutex    sync.RWMutex
}

// OrderRepoMockCreateExpectation specifies expectation struct of the OrderRepo.Create
type OrderRepoMockCreateExpectation struct {
	mock    *OrderRepoMock
	params  *OrderRepoMockCreateParams
	results *OrderRepoMockCreateResults
	Counter uint64
}

// OrderRepoMockCreateParams contains parameters of the OrderRepo.Create
type OrderRepoMockCreateParams struct {
	ctx context.Context
	i1  int64
	oa1 []models.OrderItem
}

// OrderRepoMockCreateResults contains results of the OrderRepo.Create
type OrderRepoMockCreateResults struct {
	op1 *models.Order
	err error
}

// Expect sets up expected params for OrderRepo.Create
func (mmCreate *mOrderRepoMockCreate) Expect(ctx context.Context, i1 int64, oa1 []models.OrderItem) *mOrderRepoMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OrderRepoMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &OrderRepoMockCreateExpectation{}
	}

	mmCreate.defaultExpectation.params = &OrderRepoMockCreateParams{ctx, i1, oa1}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the OrderRepo.Create
func (mmCreate *mOrderRepoMockCreate) Inspect(f func(ctx context.Context, i1 int64, oa1 []models.OrderItem)) *mOrderRepoMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for OrderRepoMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by OrderRepo.Create
func (mmCreate *mOrderRepoMockCreate) Return(op1 *models.Order, err error) *OrderRepoMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OrderRepoMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &OrderRepoMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &OrderRepoMockCreateResults{op1, err}
	return mmCreate.mock
}

// Set uses given function f to mock the OrderRepo.Create method
func (mmCreate *mOrderRepoMockCreate) Set(f func(ctx context.Context, i1 int64, oa1 []models.OrderItem) (op1 *models.Order, err error)) *OrderRepoMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the OrderRepo.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the OrderRepo.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the OrderRepo.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mOrderRepoMockCreate) When(ctx context.Context, i1 int64, oa1 []models.OrderItem) *OrderRepoMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OrderRepoMock.Create mock is already set by Set")
	}

	expectation := &OrderRepoMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &OrderRepoMockCreateParams{ctx, i1, oa1},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up OrderRepo.Create return parameters for the expectation previously defined by the When method
func (e *OrderRepoMockCreateExpectation) Then(op1 *models.Order, err error) *OrderRepoMock {
	e.results = &OrderRepoMockCreateResults{op1, err}
	return e.mock
}

// Create implements OrderRepo
func (mmCreate *OrderRepoMock) Create(ctx context.Context, i1 int64, oa1 []models.OrderItem) (op1 *models.Order, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, i1, oa1)
	}

	mm_params := OrderRepoMockCreateParams{ctx, i1, oa1}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_got := OrderRepoMockCreateParams{ctx, i1, oa1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("OrderRepoMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the OrderRepoMock.Create")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, i1, oa1)
	}
	mmCreate.t.Fatalf("Unexpected call to OrderRepoMock.Create. %v %v %v", ctx, i1, oa1)
	return
}

// CreateAfterCounter returns a count of finished OrderRepoMock.Create invocations
func (mmCreate *OrderRepoMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of OrderRepoMock.Create invocations
func (mmCreate *OrderRepoMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to OrderRepoMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mOrderRepoMockCreate) Calls() []*OrderRepoMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*OrderRepoMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *OrderRepoMock) MinimockCreateDone() bool {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateInspect logs each unmet expectation
func (m *OrderRepoMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderRepoMock.Create with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to OrderRepoMock.Create")
		} else {
			m.t.Errorf("Expected call to OrderRepoMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		m.t.Error("Expected call to OrderRepoMock.Create")
	}
}

type mOrderRepoMockSave struct {
	mock               *OrderRepoMock
	defaultExpectation *OrderRepoMockSaveExpectation
	expectations       []*OrderRepoMockSaveExpectation

	callArgs []*OrderRepoMockSaveParams
	mutex    sync.RWMutex
}

// OrderRepoMockSaveExpectation specifies expectation struct of the OrderRepo.Save
type OrderRepoMockSaveExpectation struct {
	mock    *OrderRepoMock
	params  *OrderRepoMockSaveParams
	results *OrderRepoMockSaveResults
	Counter uint64
}

// OrderRepoMockSaveParams contains parameters of the OrderRepo.Save
type OrderRepoMockSaveParams struct {
	ctx context.Context
	op1 *models.Order
}

// OrderRepoMockSaveResults contains results of the OrderRepo.Save
type OrderRepoMockSaveResults struct {
	err error
}

// Expect sets up expected params for OrderRepo.Save
func (mmSave *mOrderRepoMockSave) Expect(ctx context.Context, op1 *models.Order) *mOrderRepoMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("OrderRepoMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &OrderRepoMockSaveExpectation{}
	}

	mmSave.defaultExpectation.params = &OrderRepoMockSaveParams{ctx, op1}
	for _, e := range mmSave.expectations {
		if minimock.Equal(e.params, mmSave.defaultExpectation.params) {
			mmSave.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSave.defaultExpectation.params)
		}
	}

	return mmSave
}

// Inspect accepts an inspector function that has same arguments as the OrderRepo.Save
func (mmSave *mOrderRepoMockSave) Inspect(f func(ctx context.Context, op1 *models.Order)) *mOrderRepoMockSave {
	if mmSave.mock.inspectFuncSave != nil {
		mmSave.mock.t.Fatalf("Inspect function is already set for OrderRepoMock.Save")
	}

	mmSave.mock.inspectFuncSave = f

	return mmSave
}

// Return sets up results that will be returned by OrderRepo.Save
func (mmSave *mOrderRepoMockSave) Return(err error) *OrderRepoMock {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("OrderRepoMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &OrderRepoMockSaveExpectation{mock: mmSave.mock}
	}
	mmSave.defaultExpectation.results = &OrderRepoMockSaveResults{err}
	return mmSave.mock
}

// Set uses given function f to mock the OrderRepo.Save method
func (mmSave *mOrderRepoMockSave) Set(f func(ctx context.Context, op1 *models.Order) (err error)) *OrderRepoMock {
	if mmSave.defaultExpectation != nil {
		mmSave.mock.t.Fatalf("Default expectation is already set for the OrderRepo.Save method")
	}

	if len(mmSave.expectations) > 0 {
		mmSave.mock.t.Fatalf("Some expectations are already set for the OrderRepo.Save method")
	}

	mmSave.mock.funcSave = f
	return mmSave.mock
}

// When sets expectation for the OrderRepo.Save which will trigger the result defined by the following
// Then helper
func (mmSave *mOrderRepoMockSave) When(ctx context.Context, op1 *models.Order) *OrderRepoMockSaveExpectation {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("OrderRepoMock.Save mock is already set by Set")
	}

	expectation := &OrderRepoMockSaveExpectation{
		mock:   mmSave.mock,
		params: &OrderRepoMockSaveParams{ctx, op1},
	}
	mmSave.expectations = append(mmSave.expectations, expectation)
	return expectation
}

// Then sets up OrderRepo.Save return parameters for the expectation previously defined by the When method
func (e *OrderRepoMockSaveExpectation) Then(err error) *OrderRepoMock {
	e.results = &OrderRepoMockSaveResults{err}
	return e.mock
}

// Save implements OrderRepo
func (mmSave *OrderRepoMock) Save(ctx context.Context, op1 *models.Order) (err error) {
	mm_atomic.AddUint64(&mmSave.beforeSaveCounter, 1)
	defer mm_atomic.AddUint64(&mmSave.afterSaveCounter, 1)

	if mmSave.inspectFuncSave != nil {
		mmSave.inspectFuncSave(ctx, op1)
	}

	mm_params := OrderRepoMockSaveParams{ctx, op1}

	// Record call args
	mmSave.SaveMock.mutex.Lock()
	mmSave.SaveMock.callArgs = append(mmSave.SaveMock.callArgs, &mm_params)
	mmSave.SaveMock.mutex.Unlock()

	for _, e := range mmSave.SaveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSave.SaveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSave.SaveMock.defaultExpectation.Counter, 1)
		mm_want := mmSave.SaveMock.defaultExpectation.params
		mm_got := OrderRepoMockSaveParams{ctx, op1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSave.t.Errorf("OrderRepoMock.Save got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSave.SaveMock.defaultExpectation.results
		if mm_results == nil {
			mmSave.t.Fatal("No results are set for the OrderRepoMock.Save")
		}
		return (*mm_results).err
	}
	if mmSave.funcSave != nil {
		return mmSave.funcSave(ctx, op1)
	}
	mmSave.t.Fatalf("Unexpected call to OrderRepoMock.Save. %v %v", ctx, op1)
	return
}

// SaveAfterCounter returns a count of finished OrderRepoMock.Save invocations
func (mmSave *OrderRepoMock) SaveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.afterSaveCounter)
}

// SaveBeforeCounter returns a count of OrderRepoMock.Save invocations
func (mmSave *OrderRepoMock) SaveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.beforeSaveCounter)
}

// Calls returns a list of arguments used in each call to OrderRepoMock.Save.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSave *mOrderRepoMockSave) Calls() []*OrderRepoMockSaveParams {
	mmSave.mutex.RLock()

	argCopy := make([]*OrderRepoMockSaveParams, len(mmSave.callArgs))
	copy(argCopy, mmSave.callArgs)

	mmSave.mutex.RUnlock()

	return argCopy
}

// MinimockSaveDone returns true if the count of the Save invocations corresponds
// the number of defined expectations
func (m *OrderRepoMock) MinimockSaveDone() bool {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		return false
	}
	return true
}

// MinimockSaveInspect logs each unmet expectation
func (m *OrderRepoMock) MinimockSaveInspect() {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderRepoMock.Save with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		if m.SaveMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to OrderRepoMock.Save")
		} else {
			m.t.Errorf("Expected call to OrderRepoMock.Save with params: %#v", *m.SaveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		m.t.Error("Expected call to OrderRepoMock.Save")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockSaveInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockSaveDone()
}
