// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package orderscreator

//go:generate minimock -i route256.ozon.ru/project/loms/internal/usecases/orderscreator.ordersStorage -o orders_storage_mock_test.go -n OrdersStorageMock -p orderscreator

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/loms/internal/models"
)

// OrdersStorageMock implements ordersStorage
type OrdersStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSave          func(ctx context.Context, op1 *models.Order) (err error)
	inspectFuncSave   func(ctx context.Context, op1 *models.Order)
	afterSaveCounter  uint64
	beforeSaveCounter uint64
	SaveMock          mOrdersStorageMockSave
}

// NewOrdersStorageMock returns a mock for ordersStorage
func NewOrdersStorageMock(t minimock.Tester) *OrdersStorageMock {
	m := &OrdersStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SaveMock = mOrdersStorageMockSave{mock: m}
	m.SaveMock.callArgs = []*OrdersStorageMockSaveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrdersStorageMockSave struct {
	mock               *OrdersStorageMock
	defaultExpectation *OrdersStorageMockSaveExpectation
	expectations       []*OrdersStorageMockSaveExpectation

	callArgs []*OrdersStorageMockSaveParams
	mutex    sync.RWMutex
}

// OrdersStorageMockSaveExpectation specifies expectation struct of the ordersStorage.Save
type OrdersStorageMockSaveExpectation struct {
	mock    *OrdersStorageMock
	params  *OrdersStorageMockSaveParams
	results *OrdersStorageMockSaveResults
	Counter uint64
}

// OrdersStorageMockSaveParams contains parameters of the ordersStorage.Save
type OrdersStorageMockSaveParams struct {
	ctx context.Context
	op1 *models.Order
}

// OrdersStorageMockSaveResults contains results of the ordersStorage.Save
type OrdersStorageMockSaveResults struct {
	err error
}

// Expect sets up expected params for ordersStorage.Save
func (mmSave *mOrdersStorageMockSave) Expect(ctx context.Context, op1 *models.Order) *mOrdersStorageMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("OrdersStorageMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &OrdersStorageMockSaveExpectation{}
	}

	mmSave.defaultExpectation.params = &OrdersStorageMockSaveParams{ctx, op1}
	for _, e := range mmSave.expectations {
		if minimock.Equal(e.params, mmSave.defaultExpectation.params) {
			mmSave.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSave.defaultExpectation.params)
		}
	}

	return mmSave
}

// Inspect accepts an inspector function that has same arguments as the ordersStorage.Save
func (mmSave *mOrdersStorageMockSave) Inspect(f func(ctx context.Context, op1 *models.Order)) *mOrdersStorageMockSave {
	if mmSave.mock.inspectFuncSave != nil {
		mmSave.mock.t.Fatalf("Inspect function is already set for OrdersStorageMock.Save")
	}

	mmSave.mock.inspectFuncSave = f

	return mmSave
}

// Return sets up results that will be returned by ordersStorage.Save
func (mmSave *mOrdersStorageMockSave) Return(err error) *OrdersStorageMock {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("OrdersStorageMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &OrdersStorageMockSaveExpectation{mock: mmSave.mock}
	}
	mmSave.defaultExpectation.results = &OrdersStorageMockSaveResults{err}
	return mmSave.mock
}

// Set uses given function f to mock the ordersStorage.Save method
func (mmSave *mOrdersStorageMockSave) Set(f func(ctx context.Context, op1 *models.Order) (err error)) *OrdersStorageMock {
	if mmSave.defaultExpectation != nil {
		mmSave.mock.t.Fatalf("Default expectation is already set for the ordersStorage.Save method")
	}

	if len(mmSave.expectations) > 0 {
		mmSave.mock.t.Fatalf("Some expectations are already set for the ordersStorage.Save method")
	}

	mmSave.mock.funcSave = f
	return mmSave.mock
}

// When sets expectation for the ordersStorage.Save which will trigger the result defined by the following
// Then helper
func (mmSave *mOrdersStorageMockSave) When(ctx context.Context, op1 *models.Order) *OrdersStorageMockSaveExpectation {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("OrdersStorageMock.Save mock is already set by Set")
	}

	expectation := &OrdersStorageMockSaveExpectation{
		mock:   mmSave.mock,
		params: &OrdersStorageMockSaveParams{ctx, op1},
	}
	mmSave.expectations = append(mmSave.expectations, expectation)
	return expectation
}

// Then sets up ordersStorage.Save return parameters for the expectation previously defined by the When method
func (e *OrdersStorageMockSaveExpectation) Then(err error) *OrdersStorageMock {
	e.results = &OrdersStorageMockSaveResults{err}
	return e.mock
}

// Save implements ordersStorage
func (mmSave *OrdersStorageMock) Save(ctx context.Context, op1 *models.Order) (err error) {
	mm_atomic.AddUint64(&mmSave.beforeSaveCounter, 1)
	defer mm_atomic.AddUint64(&mmSave.afterSaveCounter, 1)

	if mmSave.inspectFuncSave != nil {
		mmSave.inspectFuncSave(ctx, op1)
	}

	mm_params := OrdersStorageMockSaveParams{ctx, op1}

	// Record call args
	mmSave.SaveMock.mutex.Lock()
	mmSave.SaveMock.callArgs = append(mmSave.SaveMock.callArgs, &mm_params)
	mmSave.SaveMock.mutex.Unlock()

	for _, e := range mmSave.SaveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSave.SaveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSave.SaveMock.defaultExpectation.Counter, 1)
		mm_want := mmSave.SaveMock.defaultExpectation.params
		mm_got := OrdersStorageMockSaveParams{ctx, op1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSave.t.Errorf("OrdersStorageMock.Save got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSave.SaveMock.defaultExpectation.results
		if mm_results == nil {
			mmSave.t.Fatal("No results are set for the OrdersStorageMock.Save")
		}
		return (*mm_results).err
	}
	if mmSave.funcSave != nil {
		return mmSave.funcSave(ctx, op1)
	}
	mmSave.t.Fatalf("Unexpected call to OrdersStorageMock.Save. %v %v", ctx, op1)
	return
}

// SaveAfterCounter returns a count of finished OrdersStorageMock.Save invocations
func (mmSave *OrdersStorageMock) SaveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.afterSaveCounter)
}

// SaveBeforeCounter returns a count of OrdersStorageMock.Save invocations
func (mmSave *OrdersStorageMock) SaveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.beforeSaveCounter)
}

// Calls returns a list of arguments used in each call to OrdersStorageMock.Save.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSave *mOrdersStorageMockSave) Calls() []*OrdersStorageMockSaveParams {
	mmSave.mutex.RLock()

	argCopy := make([]*OrdersStorageMockSaveParams, len(mmSave.callArgs))
	copy(argCopy, mmSave.callArgs)

	mmSave.mutex.RUnlock()

	return argCopy
}

// MinimockSaveDone returns true if the count of the Save invocations corresponds
// the number of defined expectations
func (m *OrdersStorageMock) MinimockSaveDone() bool {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		return false
	}
	return true
}

// MinimockSaveInspect logs each unmet expectation
func (m *OrdersStorageMock) MinimockSaveInspect() {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrdersStorageMock.Save with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		if m.SaveMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to OrdersStorageMock.Save")
		} else {
			m.t.Errorf("Expected call to OrdersStorageMock.Save with params: %#v", *m.SaveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && mm_atomic.LoadUint64(&m.afterSaveCounter) < 1 {
		m.t.Error("Expected call to OrdersStorageMock.Save")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrdersStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSaveInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrdersStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrdersStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSaveDone()
}
