// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package orderscreator

//go:generate minimock -i route256.ozon.ru/project/loms/internal/usecases/orderscreator.StockRepo -o stock_repo_mock_test.go -n StockRepoMock -p orderscreator

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/loms/internal/models"
)

// StockRepoMock implements StockRepo
type StockRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcReserve          func(ctx context.Context, oa1 []models.OrderItem) (err error)
	inspectFuncReserve   func(ctx context.Context, oa1 []models.OrderItem)
	afterReserveCounter  uint64
	beforeReserveCounter uint64
	ReserveMock          mStockRepoMockReserve
}

// NewStockRepoMock returns a mock for StockRepo
func NewStockRepoMock(t minimock.Tester) *StockRepoMock {
	m := &StockRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ReserveMock = mStockRepoMockReserve{mock: m}
	m.ReserveMock.callArgs = []*StockRepoMockReserveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStockRepoMockReserve struct {
	mock               *StockRepoMock
	defaultExpectation *StockRepoMockReserveExpectation
	expectations       []*StockRepoMockReserveExpectation

	callArgs []*StockRepoMockReserveParams
	mutex    sync.RWMutex
}

// StockRepoMockReserveExpectation specifies expectation struct of the StockRepo.Reserve
type StockRepoMockReserveExpectation struct {
	mock    *StockRepoMock
	params  *StockRepoMockReserveParams
	results *StockRepoMockReserveResults
	Counter uint64
}

// StockRepoMockReserveParams contains parameters of the StockRepo.Reserve
type StockRepoMockReserveParams struct {
	ctx context.Context
	oa1 []models.OrderItem
}

// StockRepoMockReserveResults contains results of the StockRepo.Reserve
type StockRepoMockReserveResults struct {
	err error
}

// Expect sets up expected params for StockRepo.Reserve
func (mmReserve *mStockRepoMockReserve) Expect(ctx context.Context, oa1 []models.OrderItem) *mStockRepoMockReserve {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StockRepoMock.Reserve mock is already set by Set")
	}

	if mmReserve.defaultExpectation == nil {
		mmReserve.defaultExpectation = &StockRepoMockReserveExpectation{}
	}

	mmReserve.defaultExpectation.params = &StockRepoMockReserveParams{ctx, oa1}
	for _, e := range mmReserve.expectations {
		if minimock.Equal(e.params, mmReserve.defaultExpectation.params) {
			mmReserve.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReserve.defaultExpectation.params)
		}
	}

	return mmReserve
}

// Inspect accepts an inspector function that has same arguments as the StockRepo.Reserve
func (mmReserve *mStockRepoMockReserve) Inspect(f func(ctx context.Context, oa1 []models.OrderItem)) *mStockRepoMockReserve {
	if mmReserve.mock.inspectFuncReserve != nil {
		mmReserve.mock.t.Fatalf("Inspect function is already set for StockRepoMock.Reserve")
	}

	mmReserve.mock.inspectFuncReserve = f

	return mmReserve
}

// Return sets up results that will be returned by StockRepo.Reserve
func (mmReserve *mStockRepoMockReserve) Return(err error) *StockRepoMock {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StockRepoMock.Reserve mock is already set by Set")
	}

	if mmReserve.defaultExpectation == nil {
		mmReserve.defaultExpectation = &StockRepoMockReserveExpectation{mock: mmReserve.mock}
	}
	mmReserve.defaultExpectation.results = &StockRepoMockReserveResults{err}
	return mmReserve.mock
}

// Set uses given function f to mock the StockRepo.Reserve method
func (mmReserve *mStockRepoMockReserve) Set(f func(ctx context.Context, oa1 []models.OrderItem) (err error)) *StockRepoMock {
	if mmReserve.defaultExpectation != nil {
		mmReserve.mock.t.Fatalf("Default expectation is already set for the StockRepo.Reserve method")
	}

	if len(mmReserve.expectations) > 0 {
		mmReserve.mock.t.Fatalf("Some expectations are already set for the StockRepo.Reserve method")
	}

	mmReserve.mock.funcReserve = f
	return mmReserve.mock
}

// When sets expectation for the StockRepo.Reserve which will trigger the result defined by the following
// Then helper
func (mmReserve *mStockRepoMockReserve) When(ctx context.Context, oa1 []models.OrderItem) *StockRepoMockReserveExpectation {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StockRepoMock.Reserve mock is already set by Set")
	}

	expectation := &StockRepoMockReserveExpectation{
		mock:   mmReserve.mock,
		params: &StockRepoMockReserveParams{ctx, oa1},
	}
	mmReserve.expectations = append(mmReserve.expectations, expectation)
	return expectation
}

// Then sets up StockRepo.Reserve return parameters for the expectation previously defined by the When method
func (e *StockRepoMockReserveExpectation) Then(err error) *StockRepoMock {
	e.results = &StockRepoMockReserveResults{err}
	return e.mock
}

// Reserve implements StockRepo
func (mmReserve *StockRepoMock) Reserve(ctx context.Context, oa1 []models.OrderItem) (err error) {
	mm_atomic.AddUint64(&mmReserve.beforeReserveCounter, 1)
	defer mm_atomic.AddUint64(&mmReserve.afterReserveCounter, 1)

	if mmReserve.inspectFuncReserve != nil {
		mmReserve.inspectFuncReserve(ctx, oa1)
	}

	mm_params := StockRepoMockReserveParams{ctx, oa1}

	// Record call args
	mmReserve.ReserveMock.mutex.Lock()
	mmReserve.ReserveMock.callArgs = append(mmReserve.ReserveMock.callArgs, &mm_params)
	mmReserve.ReserveMock.mutex.Unlock()

	for _, e := range mmReserve.ReserveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmReserve.ReserveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReserve.ReserveMock.defaultExpectation.Counter, 1)
		mm_want := mmReserve.ReserveMock.defaultExpectation.params
		mm_got := StockRepoMockReserveParams{ctx, oa1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReserve.t.Errorf("StockRepoMock.Reserve got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReserve.ReserveMock.defaultExpectation.results
		if mm_results == nil {
			mmReserve.t.Fatal("No results are set for the StockRepoMock.Reserve")
		}
		return (*mm_results).err
	}
	if mmReserve.funcReserve != nil {
		return mmReserve.funcReserve(ctx, oa1)
	}
	mmReserve.t.Fatalf("Unexpected call to StockRepoMock.Reserve. %v %v", ctx, oa1)
	return
}

// ReserveAfterCounter returns a count of finished StockRepoMock.Reserve invocations
func (mmReserve *StockRepoMock) ReserveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserve.afterReserveCounter)
}

// ReserveBeforeCounter returns a count of StockRepoMock.Reserve invocations
func (mmReserve *StockRepoMock) ReserveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserve.beforeReserveCounter)
}

// Calls returns a list of arguments used in each call to StockRepoMock.Reserve.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReserve *mStockRepoMockReserve) Calls() []*StockRepoMockReserveParams {
	mmReserve.mutex.RLock()

	argCopy := make([]*StockRepoMockReserveParams, len(mmReserve.callArgs))
	copy(argCopy, mmReserve.callArgs)

	mmReserve.mutex.RUnlock()

	return argCopy
}

// MinimockReserveDone returns true if the count of the Reserve invocations corresponds
// the number of defined expectations
func (m *StockRepoMock) MinimockReserveDone() bool {
	for _, e := range m.ReserveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReserveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReserveCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReserve != nil && mm_atomic.LoadUint64(&m.afterReserveCounter) < 1 {
		return false
	}
	return true
}

// MinimockReserveInspect logs each unmet expectation
func (m *StockRepoMock) MinimockReserveInspect() {
	for _, e := range m.ReserveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StockRepoMock.Reserve with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReserveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReserveCounter) < 1 {
		if m.ReserveMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StockRepoMock.Reserve")
		} else {
			m.t.Errorf("Expected call to StockRepoMock.Reserve with params: %#v", *m.ReserveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReserve != nil && mm_atomic.LoadUint64(&m.afterReserveCounter) < 1 {
		m.t.Error("Expected call to StockRepoMock.Reserve")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StockRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockReserveInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StockRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StockRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockReserveDone()
}
