// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package ordersgetter

//go:generate minimock -i route256.ozon.ru/project/loms/internal/usecases/ordersgetter.OrderRepo -o order_repo_mock_test.go -n OrderRepoMock -p ordersgetter

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"route256.ozon.ru/project/loms/internal/models"
)

// OrderRepoMock implements OrderRepo
type OrderRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLoad          func(ctx context.Context, i1 int64) (op1 *models.Order, err error)
	inspectFuncLoad   func(ctx context.Context, i1 int64)
	afterLoadCounter  uint64
	beforeLoadCounter uint64
	LoadMock          mOrderRepoMockLoad
}

// NewOrderRepoMock returns a mock for OrderRepo
func NewOrderRepoMock(t minimock.Tester) *OrderRepoMock {
	m := &OrderRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LoadMock = mOrderRepoMockLoad{mock: m}
	m.LoadMock.callArgs = []*OrderRepoMockLoadParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderRepoMockLoad struct {
	mock               *OrderRepoMock
	defaultExpectation *OrderRepoMockLoadExpectation
	expectations       []*OrderRepoMockLoadExpectation

	callArgs []*OrderRepoMockLoadParams
	mutex    sync.RWMutex
}

// OrderRepoMockLoadExpectation specifies expectation struct of the OrderRepo.Load
type OrderRepoMockLoadExpectation struct {
	mock    *OrderRepoMock
	params  *OrderRepoMockLoadParams
	results *OrderRepoMockLoadResults
	Counter uint64
}

// OrderRepoMockLoadParams contains parameters of the OrderRepo.Load
type OrderRepoMockLoadParams struct {
	ctx context.Context
	i1  int64
}

// OrderRepoMockLoadResults contains results of the OrderRepo.Load
type OrderRepoMockLoadResults struct {
	op1 *models.Order
	err error
}

// Expect sets up expected params for OrderRepo.Load
func (mmLoad *mOrderRepoMockLoad) Expect(ctx context.Context, i1 int64) *mOrderRepoMockLoad {
	if mmLoad.mock.funcLoad != nil {
		mmLoad.mock.t.Fatalf("OrderRepoMock.Load mock is already set by Set")
	}

	if mmLoad.defaultExpectation == nil {
		mmLoad.defaultExpectation = &OrderRepoMockLoadExpectation{}
	}

	mmLoad.defaultExpectation.params = &OrderRepoMockLoadParams{ctx, i1}
	for _, e := range mmLoad.expectations {
		if minimock.Equal(e.params, mmLoad.defaultExpectation.params) {
			mmLoad.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLoad.defaultExpectation.params)
		}
	}

	return mmLoad
}

// Inspect accepts an inspector function that has same arguments as the OrderRepo.Load
func (mmLoad *mOrderRepoMockLoad) Inspect(f func(ctx context.Context, i1 int64)) *mOrderRepoMockLoad {
	if mmLoad.mock.inspectFuncLoad != nil {
		mmLoad.mock.t.Fatalf("Inspect function is already set for OrderRepoMock.Load")
	}

	mmLoad.mock.inspectFuncLoad = f

	return mmLoad
}

// Return sets up results that will be returned by OrderRepo.Load
func (mmLoad *mOrderRepoMockLoad) Return(op1 *models.Order, err error) *OrderRepoMock {
	if mmLoad.mock.funcLoad != nil {
		mmLoad.mock.t.Fatalf("OrderRepoMock.Load mock is already set by Set")
	}

	if mmLoad.defaultExpectation == nil {
		mmLoad.defaultExpectation = &OrderRepoMockLoadExpectation{mock: mmLoad.mock}
	}
	mmLoad.defaultExpectation.results = &OrderRepoMockLoadResults{op1, err}
	return mmLoad.mock
}

// Set uses given function f to mock the OrderRepo.Load method
func (mmLoad *mOrderRepoMockLoad) Set(f func(ctx context.Context, i1 int64) (op1 *models.Order, err error)) *OrderRepoMock {
	if mmLoad.defaultExpectation != nil {
		mmLoad.mock.t.Fatalf("Default expectation is already set for the OrderRepo.Load method")
	}

	if len(mmLoad.expectations) > 0 {
		mmLoad.mock.t.Fatalf("Some expectations are already set for the OrderRepo.Load method")
	}

	mmLoad.mock.funcLoad = f
	return mmLoad.mock
}

// When sets expectation for the OrderRepo.Load which will trigger the result defined by the following
// Then helper
func (mmLoad *mOrderRepoMockLoad) When(ctx context.Context, i1 int64) *OrderRepoMockLoadExpectation {
	if mmLoad.mock.funcLoad != nil {
		mmLoad.mock.t.Fatalf("OrderRepoMock.Load mock is already set by Set")
	}

	expectation := &OrderRepoMockLoadExpectation{
		mock:   mmLoad.mock,
		params: &OrderRepoMockLoadParams{ctx, i1},
	}
	mmLoad.expectations = append(mmLoad.expectations, expectation)
	return expectation
}

// Then sets up OrderRepo.Load return parameters for the expectation previously defined by the When method
func (e *OrderRepoMockLoadExpectation) Then(op1 *models.Order, err error) *OrderRepoMock {
	e.results = &OrderRepoMockLoadResults{op1, err}
	return e.mock
}

// Load implements OrderRepo
func (mmLoad *OrderRepoMock) Load(ctx context.Context, i1 int64) (op1 *models.Order, err error) {
	mm_atomic.AddUint64(&mmLoad.beforeLoadCounter, 1)
	defer mm_atomic.AddUint64(&mmLoad.afterLoadCounter, 1)

	if mmLoad.inspectFuncLoad != nil {
		mmLoad.inspectFuncLoad(ctx, i1)
	}

	mm_params := OrderRepoMockLoadParams{ctx, i1}

	// Record call args
	mmLoad.LoadMock.mutex.Lock()
	mmLoad.LoadMock.callArgs = append(mmLoad.LoadMock.callArgs, &mm_params)
	mmLoad.LoadMock.mutex.Unlock()

	for _, e := range mmLoad.LoadMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmLoad.LoadMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLoad.LoadMock.defaultExpectation.Counter, 1)
		mm_want := mmLoad.LoadMock.defaultExpectation.params
		mm_got := OrderRepoMockLoadParams{ctx, i1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLoad.t.Errorf("OrderRepoMock.Load got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLoad.LoadMock.defaultExpectation.results
		if mm_results == nil {
			mmLoad.t.Fatal("No results are set for the OrderRepoMock.Load")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmLoad.funcLoad != nil {
		return mmLoad.funcLoad(ctx, i1)
	}
	mmLoad.t.Fatalf("Unexpected call to OrderRepoMock.Load. %v %v", ctx, i1)
	return
}

// LoadAfterCounter returns a count of finished OrderRepoMock.Load invocations
func (mmLoad *OrderRepoMock) LoadAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLoad.afterLoadCounter)
}

// LoadBeforeCounter returns a count of OrderRepoMock.Load invocations
func (mmLoad *OrderRepoMock) LoadBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLoad.beforeLoadCounter)
}

// Calls returns a list of arguments used in each call to OrderRepoMock.Load.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLoad *mOrderRepoMockLoad) Calls() []*OrderRepoMockLoadParams {
	mmLoad.mutex.RLock()

	argCopy := make([]*OrderRepoMockLoadParams, len(mmLoad.callArgs))
	copy(argCopy, mmLoad.callArgs)

	mmLoad.mutex.RUnlock()

	return argCopy
}

// MinimockLoadDone returns true if the count of the Load invocations corresponds
// the number of defined expectations
func (m *OrderRepoMock) MinimockLoadDone() bool {
	for _, e := range m.LoadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.LoadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterLoadCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLoad != nil && mm_atomic.LoadUint64(&m.afterLoadCounter) < 1 {
		return false
	}
	return true
}

// MinimockLoadInspect logs each unmet expectation
func (m *OrderRepoMock) MinimockLoadInspect() {
	for _, e := range m.LoadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderRepoMock.Load with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.LoadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterLoadCounter) < 1 {
		if m.LoadMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to OrderRepoMock.Load")
		} else {
			m.t.Errorf("Expected call to OrderRepoMock.Load with params: %#v", *m.LoadMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLoad != nil && mm_atomic.LoadUint64(&m.afterLoadCounter) < 1 {
		m.t.Error("Expected call to OrderRepoMock.Load")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLoadInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLoadDone()
}
